services:
  web:
    build: .
    ports:
      - "8080:5000"
    env_file:
      - .env
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"